@echo off
echo CS2 Mac Analizci kurulum basliyor...
echo Python kontrol ediliyor...
python --version
echo Kutuphaneler yukleniyor...
python -m pip install -r requirements.txt
echo Kurulum tamamlandi!
pause